### ISSUE TITLE
Request for a feature. 

### ISSUE THREAD

**Issue by shafaitahir8** [rsnpj/instagram-extension-for-chrome#1]
Could you kindly consider incorporating a feature in which replied messages are visually highlighted with a distinct color,  like it does in the mobile app? Currently, in group chats on the web version, replied messages don't receive this color highlighting, its very annoying that you miss many replied messages. It would greatly improve the user experience if this feature could be extended to the web version using a chrome extension.

Your consideration is much appreciated. Thank you!

**Comment by 0xrpj** [comment]
The project is not maintained anymore.
